name: smart_hostel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  carousel_slider: ^4.2.1
  path: any
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

